#!/bin/busybox sh
clear
echo "* Sineware Is Starting Up (Basic Initramfs) *"
mount -t proc none /proc
mount -t sysfs none /sys

echo "Loading device modules... (Coldplugging Devices)"
find /sys/devices -name modalias -type f -print0 | xargs -0 sort -u | xargs /sbin/modprobe -ab

echo "Populating /dev/"
mount -t devtmpfs none /dev

echo "Displaying bootsplash..."
clear
cat /splash.bgra > /dev/fb0

sleep 3 # enjoy that splash

cmdline() {
    local value
    value=" $(cat /proc/cmdline) "
    value="${value##* ${1}=}"
    value="${value%% *}"
    [ "${value}" != "" ] && echo "${value}"
}

rescue_shell() {
    echo "Something went wrong. Dropping to a shell."
    exec sh
}

echo "Booting from device $(cmdline root)"
mount $(cmdline root) /mnt/root || rescue_shell

mkdir /mnt/live/rom
mkdir /mnt/live/overlay

mount -t tmpfs tmpfs /mnt/live/overlay
mkdir /mnt/live/overlay/fs
mkdir /mnt/live/overlay/work

mount /mnt/root/squashfs.img /mnt/live/rom || rescue_shell

# todo openwrt does something (failsafe mode)
mount -t overlay overlay -o lowerdir=/mnt/live/rom,upperdir=/mnt/live/overlay/fs,workdir=/mnt/live/overlay/work /mnt/live
mkdir /mnt/live/system
mount $(cmdline root) /mnt/live/system

# add an if cmdline to drop to shell
#sh

# unmount, switch_root
umount /proc
umount /sys

clear

# Boot the real thing
exec switch_root /mnt/live /sbin/init || rescue_shell